import type {Metadata} from "next";
import React from "react";
import {Fira_Mono} from "next/font/google";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const firaMono = Fira_Mono({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
});

const RootLayout = ({
                        children,
                    }: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
        <body className={firaMono.className}>{children}</body>
        </html>
    );
}

export default RootLayout;